version: 1.0.{build}

skip_commits:
  message: /updated readme.*|update readme.*s/

install:
- cinst pester -y

build: false

test_script:
- ps: . .\TestModule\TestModule.Tests.ps1

artifacts:
- path: '*'
- path: '\TestModule\*'

